name: docs
on:
  push:
    branches:
      - master
jobs:
  # Build the documentation
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install DocFX
        run: choco install -y docfx

      - name: Build
        run: docfx docfx/docfx.json
      
      - name: nojekyll
        run: |
          echo $null >> .nojekyll
          echo $null >> ./docs/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
